# Generated by Django 4.0.5 on 2022-06-06 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailynotes',
            name='bacground_image',
            field=models.ImageField(blank=True, default='background.jpg', null=True, upload_to='background'),
        ),
        migrations.AlterField(
            model_name='dailynotes',
            name='note_image',
            field=models.ImageField(blank=True, default='image.jpg', null=True, upload_to='images'),
        ),
    ]
